### ISSUE TITLE
Bug: Hero video covers title and can't be muted

### ISSUE THREAD

**Issue by punit-shah** [BBCVisualJournalism/newsspec_13530#2]
Observed on Chrome 55 Linux. Not a problem in Firefox because the video does not get rendered.

I assume SMP changed how videos in 'background' mode work, because I noticed that:

- the video no longer spans the full width of the page
- the title text is hidden
- the 'Audio off/on' button is hidden, meaning that the audio cannot be muted

**Comment by punit-shah** [comment]
The hidden title and audio button can be made visible by changing the z-index of `.hero-wrapper`, though the audio button still can't be clicked.

**Comment by ChrisBAshton** [comment]
Thanks Punit. Fixed in #3.

**Comment by punit-shah** [comment]
Thanks!
